# Generated by Django 5.0.7 on 2024-08-23 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Djangohw',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('todo', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2024, 8, 23, 15, 59, 48, 861066))),
            ],
            options={
                'db_table': 'djangohw',
            },
        ),
    ]
